-----------  J O I N S   ------------
-----------1----------
SELECT LOCATION_ID,STREET_ADDRESS,CITY,
STATE_PROVINCE,COUNTRY_NAME
FROM LOCATIONS
NATURAL JOIN COUNTRIES

------------ 2 -----------
SELECT LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS
USING (DEPARTMENT_ID)

------ 3 -------
SELECT E.LAST_NAME,E.JOB_ID,E.DEPARTMENT_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN LOCATIONS Loc
ON (D.LOCATION_ID = Loc.LOCATION_ID)
WHERE LOWER(Loc.CITY) = 'washington'

----------4--------
SELECT W.LAST_NAME "EMPLOYEE",W.EMPLOYEE_ID "EMP#",
      M.LAST_NAME "MANAGER_NAME",M.MANAGER_ID "MGR#"
FROM EMPLOYEES W JOIN EMPLOYEES M
ON (W.MANAGER_ID = M.EMPLOYEE_ID)


---------5------
SELECT EMP.LAST_NAME "EMPLOYEE",EMP.EMPLOYEE_ID "EMP#",
        MGR.LAST_NAME "MANAGER_NAME",MGR.MANAGER_ID "MGR#"
FROM EMPLOYEES EMP LEFT OUTER JOIN EMPLOYEES MGR
ON (EMP.MANAGER_ID = MGR.EMPLOYEE_ID)
ORDER BY EMP.EMPLOYEE_ID


----------6---     O/P::: TOTAL 32OO RECORDS ----
SELECT EMP.LAST_NAME EMPLOYEE,EMP.DEPARTMENT_ID DEPARTMENTNO,
        COLL.LAST_NAME COLLEAGUE
FROM EMPLOYEES EMP JOIN EMPLOYEES COLL
ON(EMP.DEPARTMENT_ID = COLL.DEPARTMENT_ID)
WHERE(EMP.EMPLOYEE_ID <> COLL.EMPLOYEE_ID)
--AND EMP.FIRST_NAME = 'Daniel'
ORDER BY EMP.DEPARTMENT_ID,EMP.LAST_NAME,COLL.LAST_NAME

--SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL
--FROM EMPLOYEES EMP
--GROUP BY DEPARTMENT_ID



-------  8  -----
SELECT EMP.LAST_NAME,EMP.HIRE_DATE
FROM EMPLOYEES EMP 
   JOIN EMPLOYEES DAVIES 
ON (DAVIES.LAST_NAME = 'Davies')
WHERE DAVIES.HIRE_DATE > EMP.HIRE_DATE
ORDER BY EMP.HIRE_DATE

---  9  -------------
SELECT EMP.LAST_NAME,EMP.HIRE_DATE,
        MGR.LAST_NAME,MGR.HIRE_DATE
FROM EMPLOYEES EMP JOIN EMPLOYEES MGR
ON(MGR.MANAGER_ID = EMP.EMPLOYEE_ID)
WHERE MGR.HIRE_DATE > EMP.HIRE_DATE


