
-------------------LESSON -1 ( SELECT STATEMENTS ONLY ) ---------------------

SELECT last_Name,job_id,Salary AS sal 
FROM EMPLOYEES

SELECT * 
FROM JOB_HISTORY

SELECT *
FROM DEPARTMENTS

SELECT MANAGER_ID,DEPARTMENT_ID,FIRST_NAME
FROM EMPLOYEES

SELECT FIRST_NAME,SALARY*5 AS SAL
FROM EMPLOYEES

SELECT DEPARTMENT_ID,JOB_ID,START_DATE AS HIRE_DATE,EMPLOYEE_ID
FROM JOB_HISTORY
--- this is a comment line
---" all unique job IDs from the EMPLOYEES table. WE USED THE KEYWORD "DISTINCT" 
SELECT DISTINCT JOB_ID
FROM EMPLOYEES

SELECT EMPLOYEE_ID AS EMP#,LAST_NAME AS EMPLOYEE,JOB_ID AS JOB,HIRE_DATE AS STARTDATE
FROM EMPLOYEES

SELECT LAST_NAME ||', '||JOB_ID  "EMPLOYEE AND TITLE"
FROM EMPLOYEES

SELECT EMPLOYEE_ID||', '||FIRST_NAME||', '||LAST_NAME
||', '||EMAIL||', '||PHONE_NUMBER||', '
||HIRE_DATE||', '||JOB_ID||', '||SALARY||', '
||COMMISSION_PCT||', '||MANAGER_ID||', '||DEPARTMENT_ID
FROM EMPLOYEES
