--------------S I N G L E   R O W   F U N C T I O N S ---------------------

-----Displaying the system date with this function and DUAL is the temporary table----
SELECT SYSDATE "SYSTEM DATE" 
FROM DUAL

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,
ROUND(SALARY*1.155,0)"New Salary"
FROM EMPLOYEES

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,
ROUND(SALARY*1.155,0)"New Salary",
ROUND(SALARY*1.155,0)-SALARY "Increase"
FROM EMPLOYEES

-------5A-----
SELECT INITCAP(LAST_NAME) "NAME",
LENGTH(LAST_NAME) "LENGTH"
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%'
OR LAST_NAME LIKE 'M%'
OR LAST_NAME LIKE 'A%'
ORDER BY LAST_NAME

----------5B ---""& ""IS FOR THE PROMPTED FOR THE DIALOGUE BOX---
SELECT INITCAP(LAST_NAME) "NAME",
LENGTH(LAST_NAME) "LENGTH"
FROM EMPLOYEES
WHERE LAST_NAME LIKE '&START_LETTER%'
ORDER BY LAST_NAME

------BOTH 5C ARE SAME EXCEPT UPPER----
SELECT INITCAP(LAST_NAME) "NAME",
LENGTH(LAST_NAME) "LENGTH"
FROM EMPLOYEES
WHERE LAST_NAME LIKE UPPER('&START_LETTER%')
ORDER BY LAST_NAME

--------6---------
SELECT LAST_NAME,ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)) MONTHS_WORKED
FROM EMPLOYEES
ORDER BY MONTHS_WORKED


----7-----
SELECT LAST_NAME,LPAD(SALARY,15,'$') SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC

-----8-- TRICKY   ----
SELECT RPAD(LAST_NAME,8)||' '|| 
  RPAD(' ', SALARY/1000+1, '*') 
    EMPLOYEES_AND_THEIR_SALARIES
FROM EMPLOYEES
ORDER BY SALARY DESC

--------9------
SELECT LAST_NAME,TRUNC((SYSDATE-HIRE_DATE)/7) TENURE
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90
ORDER BY TENURE DESC





